#!/bin/bash -e

run_postgres_on_start() {
    echo "Configuring postgres to run on startup..."
    pg_ctl -D /usr/local/var/postgres start && brew services start postgresql
}

create_ibyrd_user () {
    echo "Creating a new postgres role and user named 'ibyrd'..."
    read -sp 'Please provide a password: ' passinput
    exec psql  postgres -c '\x' -c "CREATE DATABASE ibyrd;"
    exec psql -d 'ibyrd' -c '\x' -c 'CREATE ROLE ibyrd WITH LOGIN CREATEDB PASSWORD '$passinput';'
    exec psql -d 'ibyrd' -c '\x' -c "ALTER ROLE ibyrd CREATEDB;"
    echo
    echo "Thank you, a new postgres role and db have been created!"
}

# # Uncomment to run Postgres on start
# run_postgres_on_start

# TODO: Additional testing
create_ibyrd_user
